# Site settings
title: Checkvistle
email: checkvistle@techmyway.com
description: > # this means to ignore newlines until "baseurl:"
  Checkvistle description
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://checkvistle.techmyway.com" # the base hostname & protocol for your site
twitter_username: checkvistle

# Build settings
markdown: kramdown
